// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React         = require("react");
var ReasonReact   = require("reason-react/src/ReasonReact.js");
var Vrroom$Vrroom = require("../src/Vrroom.bs.js");

var instance = ReasonReact.statelessComponent("ThreeItems");

function make() {
  var newrecord = instance.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Vrroom$Vrroom.Fragment[/* make */0](/* array */[
                      React.createElement("li", undefined, Vrroom$Vrroom.Helpers[/* text */0]("Item 1")),
                      React.createElement("li", undefined, Vrroom$Vrroom.Helpers[/* text */0]("Item 2")),
                      React.createElement("li", undefined, Vrroom$Vrroom.Helpers[/* text */0]("Item 3"))
                    ]));
    });
  return newrecord;
}

var ThreeItems = /* module */[
  /* instance */instance,
  /* make */make
];

var instance$1 = ReasonReact.statelessComponent("Fragment example");

function make$1() {
  var newrecord = instance$1.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("ol", undefined, React.createElement("li", undefined, Vrroom$Vrroom.Helpers[/* text */0]("Item 0")), ReasonReact.element(/* None */0, /* None */0, make(/* array */[])), React.createElement("li", undefined, Vrroom$Vrroom.Helpers[/* text */0]("Item 4")));
    });
  return newrecord;
}

exports.ThreeItems = ThreeItems;
exports.instance   = instance$1;
exports.make       = make$1;
/* instance Not a pure module */
