// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Vrroom = require("../src/Vrroom.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var maybeErrorClass = /* Some */["is-oops"];

var instance = ReasonReact.statelessComponent("ClassName example");

function make() {
  return /* record */[
          /* debugName */instance[/* debugName */0],
          /* reactClassInternal */instance[/* reactClassInternal */1],
          /* handedOffState */instance[/* handedOffState */2],
          /* willReceiveProps */instance[/* willReceiveProps */3],
          /* didMount */instance[/* didMount */4],
          /* didUpdate */instance[/* didUpdate */5],
          /* willUnmount */instance[/* willUnmount */6],
          /* willUpdate */instance[/* willUpdate */7],
          /* shouldUpdate */instance[/* shouldUpdate */8],
          /* render */(function () {
              var className = Curry._1(Vrroom.Helpers[/* ClassName */5][/* join */0], /* :: */[
                    "tooltip",
                    /* :: */[
                      Curry._2(Vrroom.Helpers[/* ClassName */5][/* if_ */1], true, "s-hovered"),
                      /* :: */[
                        Curry._1(Vrroom.Helpers[/* ClassName */5][/* fromOption */2], maybeErrorClass),
                        /* [] */0
                      ]
                    ]
                  ]);
              return React.createElement("div", undefined, React.createElement("div", {
                              className: className
                            }, Vrroom.text("Hello world!")), React.createElement("div", {
                              className: Curry._1(Vrroom.Helpers[/* ClassName */5][/* join */0], /* :: */[
                                    "tooltip",
                                    /* :: */[
                                      Curry._2(Vrroom.Helpers[/* ClassName */5][/* if_ */1], true, "s-hovered"),
                                      /* [] */0
                                    ]
                                  ])
                            }, Vrroom.text("Hello world!")));
            }),
          /* initialState */instance[/* initialState */10],
          /* retainedProps */instance[/* retainedProps */11],
          /* reducer */instance[/* reducer */12],
          /* subscriptions */instance[/* subscriptions */13],
          /* jsElementWrapped */instance[/* jsElementWrapped */14]
        ];
}

var isHovered = true;

exports.maybeErrorClass = maybeErrorClass;
exports.isHovered = isHovered;
exports.instance = instance;
exports.make = make;
/* instance Not a pure module */
