// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var Vrroom      = require("../src/Vrroom.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var instance = ReasonReact.statelessComponent("Control.If example");

function make() {
  var newrecord = instance.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, Vrroom.Helpers[/* text */1]("Hello"), ReasonReact.element(/* None */0, /* None */0, Curry._2(Vrroom.Control[/* If */2][/* make */1], /* true */1, (function () {
                            return Vrroom.Helpers[/* text */1]("Hello");
                          }))));
    });
  return newrecord;
}

var showHello = /* true */1;

exports.showHello = showHello;
exports.instance  = instance;
exports.make      = make;
/* instance Not a pure module */
