// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Vrroom = require("../src/Vrroom.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var instance = ReasonReact.statelessComponent("Control.If example");

function make() {
  return /* record */[
          /* debugName */instance[/* debugName */0],
          /* reactClassInternal */instance[/* reactClassInternal */1],
          /* handedOffState */instance[/* handedOffState */2],
          /* willReceiveProps */instance[/* willReceiveProps */3],
          /* didMount */instance[/* didMount */4],
          /* didUpdate */instance[/* didUpdate */5],
          /* willUnmount */instance[/* willUnmount */6],
          /* willUpdate */instance[/* willUpdate */7],
          /* shouldUpdate */instance[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, "Hello", ReasonReact.element(/* None */0, /* None */0, Curry._2(Vrroom.Control[/* If */2][/* make */1], true, (function () {
                                    return Vrroom.text("Hello");
                                  }))));
            }),
          /* initialState */instance[/* initialState */10],
          /* retainedProps */instance[/* retainedProps */11],
          /* reducer */instance[/* reducer */12],
          /* subscriptions */instance[/* subscriptions */13],
          /* jsElementWrapped */instance[/* jsElementWrapped */14]
        ];
}

var showHello = true;

exports.showHello = showHello;
exports.instance = instance;
exports.make = make;
/* instance Not a pure module */
