// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Vrroom = require("../src/Vrroom.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var maybeError = /* Some */["oops!"];

var instance = ReasonReact.statelessComponent("Control.IfSome example");

function make() {
  return /* record */[
          /* debugName */instance[/* debugName */0],
          /* reactClassInternal */instance[/* reactClassInternal */1],
          /* handedOffState */instance[/* handedOffState */2],
          /* willReceiveProps */instance[/* willReceiveProps */3],
          /* didMount */instance[/* didMount */4],
          /* didUpdate */instance[/* didUpdate */5],
          /* willUnmount */instance[/* willUnmount */6],
          /* willUpdate */instance[/* willUpdate */7],
          /* shouldUpdate */instance[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, maybeError ? "oops!" : null, ReasonReact.element(/* None */0, /* None */0, Curry._2(Vrroom.Control[/* IfSome */3][/* make */1], maybeError, Vrroom.text)));
            }),
          /* initialState */instance[/* initialState */10],
          /* retainedProps */instance[/* retainedProps */11],
          /* reducer */instance[/* reducer */12],
          /* subscriptions */instance[/* subscriptions */13],
          /* jsElementWrapped */instance[/* jsElementWrapped */14]
        ];
}

exports.maybeError = maybeError;
exports.instance = instance;
exports.make = make;
/* instance Not a pure module */
