// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React                 = require("react");
var ReactDOMRe            = require("reason-react/src/ReactDOMRe.js");
var Pure$Vrroom           = require("./pure.bs.js");
var ReasonReact           = require("reason-react/src/ReasonReact.js");
var Fragment$Vrroom       = require("./Fragment.bs.js");
var ControlIf$Vrroom      = require("./ControlIf.bs.js");
var ControlMap$Vrroom     = require("./ControlMap.bs.js");
var ControlIfSome$Vrroom  = require("./ControlIfSome.bs.js");
var ControlMapList$Vrroom = require("./ControlMapList.bs.js");

var instance = ReasonReact.statelessComponent("Page");

function make() {
  var newrecord = instance.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, Pure$Vrroom.make(/* array */[])), ReasonReact.element(/* None */0, /* None */0, Fragment$Vrroom.make(/* array */[])), ReasonReact.element(/* None */0, /* None */0, ControlMap$Vrroom.make(/* array */[])), ReasonReact.element(/* None */0, /* None */0, ControlMapList$Vrroom.make(/* array */[])), ReasonReact.element(/* None */0, /* None */0, ControlIf$Vrroom.make(/* array */[])), ReasonReact.element(/* None */0, /* None */0, ControlIfSome$Vrroom.make(/* array */[])));
    });
  return newrecord;
}

var Page = /* module */[
  /* instance */instance,
  /* make */make
];

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, make(/* array */[])), "index");

exports.Page = Page;
/* instance Not a pure module */
