// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Pure           = require("./pure.bs.js");
var React          = require("react");
var Vrroom         = require("../src/Vrroom.bs.js");
var ControlIf      = require("./ControlIf.bs.js");
var ControlMap     = require("./ControlMap.bs.js");
var ReactDOMRe     = require("reason-react/src/ReactDOMRe.js");
var ReasonReact    = require("reason-react/src/ReasonReact.js");
var ControlIfSome  = require("./ControlIfSome.bs.js");
var ControlMapList = require("./ControlMapList.bs.js");

var instance = ReasonReact.statelessComponent("Page");

function make() {
  var newrecord = instance.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, Pure.make(/* array */[])), ReasonReact.element(/* None */0, /* None */0, Vrroom.Fragment[/* make */0](/* array */[])), ReasonReact.element(/* None */0, /* None */0, ControlMap.make(/* array */[])), ReasonReact.element(/* None */0, /* None */0, ControlMapList.make(/* array */[])), ReasonReact.element(/* None */0, /* None */0, ControlIf.make(/* array */[])), ReasonReact.element(/* None */0, /* None */0, ControlIfSome.make(/* array */[])));
    });
  return newrecord;
}

var Page = /* module */[
  /* instance */instance,
  /* make */make
];

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, make(/* array */[])), "index");

exports.Page = Page;
/* instance Not a pure module */
