// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var Vrroom      = require("../src/Vrroom.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var instance = ReasonReact.statelessComponent("Item");

function make(label, _) {
  var newrecord = instance.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("li", undefined, Vrroom.Helpers[/* text */0](label));
    });
  return newrecord;
}

var ItemBefore = /* module */[
  /* instance */instance,
  /* make */make
];

var make$1 = Vrroom.pure((function (render, label) {
        return Curry._1(render, React.createElement("li", undefined, Vrroom.Helpers[/* text */0](label)));
      }));

var Item = /* module */[/* make */make$1];

var instance$1 = ReasonReact.statelessComponent("Pure example");

function make$2() {
  var newrecord = instance$1.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("ul", undefined, ReasonReact.element(/* None */0, /* None */0, Curry._2(make$1, "apples", /* int array */[])), ReasonReact.element(/* None */0, /* None */0, Curry._2(make$1, "bananas", /* int array */[])), ReasonReact.element(/* None */0, /* None */0, Curry._2(make$1, "coconuts", /* int array */[])));
    });
  return newrecord;
}

exports.ItemBefore = ItemBefore;
exports.Item       = Item;
exports.instance   = instance$1;
exports.make       = make$2;
/* instance Not a pure module */
