// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Vrroom = require("../src/Vrroom.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var instance = ReasonReact.statelessComponent("Item");

function make(label, _) {
  return /* record */[
          /* debugName */instance[/* debugName */0],
          /* reactClassInternal */instance[/* reactClassInternal */1],
          /* handedOffState */instance[/* handedOffState */2],
          /* willReceiveProps */instance[/* willReceiveProps */3],
          /* didMount */instance[/* didMount */4],
          /* didUpdate */instance[/* didUpdate */5],
          /* willUnmount */instance[/* willUnmount */6],
          /* willUpdate */instance[/* willUpdate */7],
          /* shouldUpdate */instance[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("li", undefined, label);
            }),
          /* initialState */instance[/* initialState */10],
          /* retainedProps */instance[/* retainedProps */11],
          /* reducer */instance[/* reducer */12],
          /* subscriptions */instance[/* subscriptions */13],
          /* jsElementWrapped */instance[/* jsElementWrapped */14]
        ];
}

var ItemBefore = /* module */[
  /* instance */instance,
  /* make */make
];

var make$1 = Vrroom.pure((function (render, label) {
        return Curry._1(render, React.createElement("li", undefined, Vrroom.text(label)));
      }));

var Item = /* module */[/* make */make$1];

var instance$1 = ReasonReact.statelessComponent("Pure example");

function make$2() {
  return /* record */[
          /* debugName */instance$1[/* debugName */0],
          /* reactClassInternal */instance$1[/* reactClassInternal */1],
          /* handedOffState */instance$1[/* handedOffState */2],
          /* willReceiveProps */instance$1[/* willReceiveProps */3],
          /* didMount */instance$1[/* didMount */4],
          /* didUpdate */instance$1[/* didUpdate */5],
          /* willUnmount */instance$1[/* willUnmount */6],
          /* willUpdate */instance$1[/* willUpdate */7],
          /* shouldUpdate */instance$1[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("ul", undefined, ReasonReact.element(/* None */0, /* None */0, Curry._2(make$1, "apples", /* array */[])), ReasonReact.element(/* None */0, /* None */0, Curry._2(make$1, "bananas", /* array */[])), ReasonReact.element(/* None */0, /* None */0, Curry._2(make$1, "coconuts", /* array */[])));
            }),
          /* initialState */instance$1[/* initialState */10],
          /* retainedProps */instance$1[/* retainedProps */11],
          /* reducer */instance$1[/* reducer */12],
          /* subscriptions */instance$1[/* subscriptions */13],
          /* jsElementWrapped */instance$1[/* jsElementWrapped */14]
        ];
}

exports.ItemBefore = ItemBefore;
exports.Item = Item;
exports.instance = instance$1;
exports.make = make$2;
/* instance Not a pure module */
